name: Compile and push file to release

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create font folder
        run: mkdir ~/.local/share/fonts
        
      - name: Move fonts
        run: mv -v fonts/* ~/.local/share/fonts
              
      - name: Refresh font cache
        run: fc-cache -f -v
        
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.AUTO_RELEASE_TOKEN }}
          
      - name: Run Tectonic
        run: tectonic main.tex
        
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: main.pdf
      - uses: actions/checkout@v1
