name: Compile and push file to release

on:
  push:
    branches: [ main, font_test ]

jobs:
  build_latex:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Move ttf fonts
        run: mv -v fonts/*.ttf /usr/share/fonts/truetype

      - name: Create opentype directory
        run: mkdir /usr/share/fonts/opentype
      - name: Move otf fonts
        run: mv -v fonts/*.otf /usr/share/fonts/opentype
              
      - name: Refresh font cache
        run: fc-cache -f -v
        
      - name: Display installed fonts for debugging
        run: fc-list
        
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.AUTO_RELEASE_TOKEN }}
          
      - name: Run Tectonic
        run: tectonic main.tex
        
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: main.pdf
      - uses: actions/checkout@v1
