name: Compile and push file to release

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Compilation
        uses: vinay0410/tectonic-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE_TOKEN }}
        with:
          tex_path: 'main.tex'
          push: 'yes'
